# Example Files

- 3d.R - Shows how to add PSTricks macro calls (see Section \@ref(extending-for-unlayered-macro-packages)).

- basic.R - An example without using geoms.

- dots.R - Shows available dots in different styles.

- engines.R - Tests the engines that produce a .pdf from a .tex file.
  The "pdflatex" engine gives a two page .pdf when using landscape (could be prevented
  by using a smaller pspicture size). Also tests opacity.
  See Section \@ref(the-configuration-file).

- example.R - A simple example with a geom.

- ggstyle.R - Tries to generate a plot with a ggplot style (see Section \@ref(geomaxesgrid)).

- mtcars.R - Demonstrates how to print text labels (see Section \@ref(strings-as-tick-labels)).

- nainf.R - Shows handling of NaNs and Infs (see Section \@ref(line-geoms)).

- noshow.R - Demonstrates scaling without an axis (see Section \@ref(options)).

- oneliner.R - A plot generated by just one line.

- pictures.R - Two pictures showing the difference in clipping (see Section \@ref(scaling-and-clipping)).

- psttoeps.R and psttoeps2.R - Tests of the PSTtoEps functionality (see Section \@ref(options)).

- resetoptions.R - Shows that a new picture resets most options (see Chapter \@ref(pictures)).

- secondary.R - Tests of secondary axes (see Section \@ref(options)).

- subplot.R - Tests of subplot options (see Chapter \@ref(pictures)).

- subplotl.R - Tests of subplot options on landscape paper (see Chapter \@ref(pictures)).

- ticks.R - Examples of setting tickmarks.

- tiger.R - Tests including the "tiger.eps" file.

- toeps.R - Test of generating a .eps file (possibly for including in other documents).

## Running all examples

The script "examples/examples.sh" runs the above scripts, as well as runs all examples
given with the documentation (so that these are not only tested, but their output
may be viewed), with the output in
directories named after the R script where these are located. Script "examples/clean.sh" may
be used to clean up.
